resources : struct
{
    sorcerer_texture: TextureFile = .{ path = "data://aseprite/sorcerer.png" };
    sorcerer_aseprite: AsepriteFile = .{ path = "data://aseprite/sorcerer.json" };

    fireball_texture: TextureFile = .{ path = "data://aseprite/fireball.png" };
    fireball_aseprite: AsepriteFile = .{ path = "data://aseprite/fireball.json" };

    tree_texture: TextureFile = .{ path = "data://aseprite/tree.png" };
    tree_aseprite: AsepriteFile = .{ path = "data://aseprite/tree.json" };
};
