resources : struct
{
    sprite_shader: Shader = .{ fs_path = "data://shaders/sprite.fs" };

    // ACTORS

    mage_texture: TextureFile = .{ path = "data://aseprite/mage.png" };
    mage_aseprite: AsepriteFile = .{ path = "data://aseprite/mage.json" };

    mage2_texture: TextureFile = .{ path = "data://aseprite/mage2.png" };
    mage2_aseprite: AsepriteFile = .{ path = "data://aseprite/mage2.json" };

    mage3_texture: TextureFile = .{ path = "data://aseprite/mage3.png" };
    mage3_aseprite: AsepriteFile = .{ path = "data://aseprite/mage3.json" };

    mage4_texture: TextureFile = .{ path = "data://aseprite/mage4.png" };
    mage4_aseprite: AsepriteFile = .{ path = "data://aseprite/mage4.json" };

    tree_texture: TextureFile = .{ path = "data://aseprite/tree.png" };
    tree_aseprite: AsepriteFile = .{ path = "data://aseprite/tree.json" };

    goblin_texture: TextureFile = .{ path = "data://aseprite/goblin.png" };
    goblin_aseprite: AsepriteFile = .{ path = "data://aseprite/goblin.json" };

    bookshelf_texture: TextureFile = .{ path = "data://aseprite/bookshelf.png" };
    bookshelf_aseprite: AsepriteFile = .{ path = "data://aseprite/bookshelf.json" };

    book_texture: TextureFile = .{ path = "data://aseprite/book.png" };
    book_aseprite: AsepriteFile = .{ path = "data://aseprite/book.json" };

    cheese_texture: TextureFile = .{ path = "data://aseprite/cheese.png" };
    cheese_aseprite: AsepriteFile = .{ path = "data://aseprite/cheese.json" };

    chest_texture: TextureFile = .{ path = "data://aseprite/chest.png" };
    chest_aseprite: AsepriteFile = .{ path = "data://aseprite/chest.json" };

    ghost_texture: TextureFile = .{ path = "data://aseprite/ghost.png" };
    ghost_aseprite: AsepriteFile = .{ path = "data://aseprite/ghost.json" };

    tomb1_texture: TextureFile = .{ path = "data://aseprite/tomb1.png" };
    tomb1_aseprite: AsepriteFile = .{ path = "data://aseprite/tomb1.json" };

    tomb2_texture: TextureFile = .{ path = "data://aseprite/tomb2.png" };
    tomb2_aseprite: AsepriteFile = .{ path = "data://aseprite/tomb2.json" };

    brain_texture: TextureFile = .{ path = "data://aseprite/brain.png" };
    brain_aseprite: AsepriteFile = .{ path = "data://aseprite/brain.json" };


    // SPELL EFFECTS

    fireball_texture: TextureFile = .{ path = "data://aseprite/fireball.png" };
    fireball_aseprite: AsepriteFile = .{ path = "data://aseprite/fireball.json" };

    flame_texture: TextureFile = .{ path = "data://aseprite/flame.png" };
    flame_aseprite: AsepriteFile = .{ path = "data://aseprite/flame.json" };

    explosion_texture: TextureFile = .{ path = "data://aseprite/explosion.png" };
    explosion_aseprite: AsepriteFile = .{ path = "data://aseprite/explosion.json" };

    lobotomie_texture: TextureFile = .{ path = "data://aseprite/lobotomie.png" };
    lobotomie_aseprite: AsepriteFile = .{ path = "data://aseprite/lobotomie.json" };

    sentification_texture: TextureFile = .{ path = "data://aseprite/sentification.png" };
    sentification_aseprite: AsepriteFile = .{ path = "data://aseprite/sentification.json" };

    healing_texture: TextureFile = .{ path = "data://aseprite/healing.png" };
    healing_aseprite: AsepriteFile = .{ path = "data://aseprite/healing.json" };

    transposition_texture: TextureFile = .{ path = "data://aseprite/transposition.png" };
    transposition_aseprite: AsepriteFile = .{ path = "data://aseprite/transposition.json" };

    reanimation_texture: TextureFile = .{ path = "data://aseprite/reanimation.png" };
    reanimation_aseprite: AsepriteFile = .{ path = "data://aseprite/reanimation.json" };

    darkbook_texture: TextureFile = .{ path = "data://aseprite/darkbook.png" };
    darkbook_aseprite: AsepriteFile = .{ path = "data://aseprite/darkbook.json" };

    skull_texture: TextureFile = .{ path = "data://aseprite/skull.png" };
    skull_aseprite: AsepriteFile = .{ path = "data://aseprite/skull.json" };

    cupidon_texture: TextureFile = .{ path = "data://aseprite/cupidon.png" };
    cupidon_aseprite: AsepriteFile = .{ path = "data://aseprite/cupidon.json" };

    illusion_texture: TextureFile = .{ path = "data://aseprite/illusion.png" };
    illusion_aseprite: AsepriteFile = .{ path = "data://aseprite/illusion.json" };

    portalgraveyard_texture: TextureFile = .{ path = "data://aseprite/portalgraveyard.png" };
    portalgraveyard_aseprite: AsepriteFile = .{ path = "data://aseprite/portalgraveyard.json" };

    portalvolcano_texture: TextureFile = .{ path = "data://aseprite/portalvolcano.png" };
    portalvolcano_aseprite: AsepriteFile = .{ path = "data://aseprite/portalvolcano.json" };

    portallibrary_texture: TextureFile = .{ path = "data://aseprite/portallibrary.png" };
    portallibrary_aseprite: AsepriteFile = .{ path = "data://aseprite/portallibrary.json" };

    portalbrain_texture: TextureFile = .{ path = "data://aseprite/portalbrain.png" };
    portalbrain_aseprite: AsepriteFile = .{ path = "data://aseprite/portalbrain.json" };
    
    portalforest_texture: TextureFile = .{ path = "data://aseprite/portalforest.png" };
    portalforest_aseprite: AsepriteFile = .{ path = "data://aseprite/portalforest.json" };


    // OTHER

    icons_texture: TextureFile = .{ path = "data://aseprite/icons.png" };
    icons_aseprite: AsepriteFile = .{ path = "data://aseprite/icons.json" };

    faces_texture: TextureFile = .{ path = "data://aseprite/faces.png" };
    faces_aseprite: AsepriteFile = .{ path = "data://aseprite/faces.json" };

    attack_smear_texture: TextureFile = .{ path = "data://aseprite/attack_smear.png" };
    attack_smear_aseprite: AsepriteFile = .{ path = "data://aseprite/attack_smear.json" };

    rug1_texture: TextureFile = .{ path = "data://aseprite/rug1.png" };
    rug1_aseprite: AsepriteFile = .{ path = "data://aseprite/rug1.json" };

    rug2_texture: TextureFile = .{ path = "data://aseprite/rug2.png" };
    rug2_aseprite: AsepriteFile = .{ path = "data://aseprite/rug2.json" };

    rug3_texture: TextureFile = .{ path = "data://aseprite/rug3.png" };
    rug3_aseprite: AsepriteFile = .{ path = "data://aseprite/rug3.json" };

    rug4_texture: TextureFile = .{ path = "data://aseprite/rug4.png" };
    rug4_aseprite: AsepriteFile = .{ path = "data://aseprite/rug4.json" };

    rug5_texture: TextureFile = .{ path = "data://aseprite/rug5.png" };
    rug5_aseprite: AsepriteFile = .{ path = "data://aseprite/rug5.json" };

    treetray_texture: TextureFile = .{ path = "data://aseprite/treetray.png" };
    treetray_aseprite: AsepriteFile = .{ path = "data://aseprite/treetray.json" };

    bush_texture: TextureFile = .{ path = "data://aseprite/bush.png" };
    bush_aseprite: AsepriteFile = .{ path = "data://aseprite/bush.json" };

    grid_texture: TextureFile = .{ path = "data://aseprite/grid.png" };
    grid_aseprite: AsepriteFile = .{ path = "data://aseprite/grid.json" };

    slab_texture: TextureFile = .{ path = "data://aseprite/slab.png" };
    slab_aseprite: AsepriteFile = .{ path = "data://aseprite/slab.json" };

    patchlibrary_texture: TextureFile = .{ path = "data://aseprite/patch_library.png" };
    patchlibrary_aseprite: AsepriteFile = .{ path = "data://aseprite/patch_library.json" };

    // TILES

    tile_wood_1_texture: TextureFile = .{ path = "data://aseprite/tile_wood_1.png" };
    tile_wood_1_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_wood_1.json" };

    tile_wood_2_texture: TextureFile = .{ path = "data://aseprite/tile_wood_2.png" };
    tile_wood_2_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_wood_2.json" };

    tile_wood_3_texture: TextureFile = .{ path = "data://aseprite/tile_wood_3.png" };
    tile_wood_3_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_wood_3.json" };

    tile_wood_4_texture: TextureFile = .{ path = "data://aseprite/tile_wood_4.png" };
    tile_wood_4_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_wood_4.json" };

    tile_wood_5_texture: TextureFile = .{ path = "data://aseprite/tile_wood_5.png" };
    tile_wood_5_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_wood_5.json" };


    tile_rock_1_texture: TextureFile = .{ path = "data://aseprite/tile_rock_1.png" };
    tile_rock_1_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_rock_1.json" };

    tile_rock_2_texture: TextureFile = .{ path = "data://aseprite/tile_rock_2.png" };
    tile_rock_2_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_rock_2.json" };

    tile_rock_3_texture: TextureFile = .{ path = "data://aseprite/tile_rock_3.png" };
    tile_rock_3_aseprite: AsepriteFile = .{ path = "data://aseprite/tile_rock_3.json" };

};
